### ISSUE TITLE
Mobile version wont allow me to draw even a single line

### ISSUE THREAD

**Issue by rachyharkov** [Zzzul/paint-wannabe#1]
Idk why, you might want to fix these

![Screenshot_20220911-180949.png](https://user-images.githubusercontent.com/44340813/189524304-d06cf0da-4efd-4bb2-bcae-5fea396886e0.png)

instead drawing a line, it only allow me to tap on canvas that only dot can be drawed like picture above...

this happened only on mobile device

🙏🏽🙏🏽🙏🏽

**Comment by Zzzul** [comment]
No, it still doesn't work.
but when I tried on [mobile simulator](https://chrome.google.com/webstore/detail/mobile-simulator-responsi/ckejmhbmlajgoklhgbapkiccekfoccmk)  it`s work

<img width="248" alt="image" src="https://user-images.githubusercontent.com/62506582/189611955-80245b95-4442-4dc6-a623-226f2fdd0064.png">

**Comment by rachyharkov** [comment]
a'ight, i'm still having this issue, please keep this issue open, i want to help, tqqq

**Comment by rachyharkov** [comment]
great!
